### ISSUE TITLE
Issue with autoloading

### ISSUE THREAD

**Issue by Trainmaster** [kelunik/gateway#1]
The directory structure is as follows:

```
<root>/<someDir>/vendor/bin/gateway
<root>/script/server
<root>/server.php
```

`<root>/script/server` looks like
```
php $PHP_FLAGS -c php.ini <someDir>/vendor/bin/gateway -S $HOST:$PORT -s $PWD/server.php -d $PWD
```

Being in the `<root>` directory I run `./script/server` but then I get the following error:

```
PHP Warning:  require(<rootDir>/<someDir>/vendor/kelunik/gateway/bin/../vendor/autoload.php): failed to open stream: No such file or directory in <rootDir>/<someDir>/vendor/kelunik/gateway/bin/gateway on line 22
```

I looked at `vendor/bin/gateway` and changed:
`require __DIR__ . '/../vendor/autoload.php';`
to
`require __DIR__ . '/../../../autoload.php';`

Then it works. But I'm not sure if that's a general solution. Looking at other bin files like `phpcs` or `phpunit` there seem to be different ways to get it working.

**Comment by kelunik** [comment]
Will fix it later. Thanks for the report!

**Comment by kelunik** [comment]
Should be fixed via https://github.com/kelunik/gateway/commit/a0507fd66f7e195c7f6c58c14cab74c06cb929ec.
