### ISSUE TITLE
Wrong content-type in response headers for stylesheets

### ISSUE THREAD

**Issue by Trainmaster** [kelunik/gateway#5]
Any `*.css` files are served with `content-type: text/plain; charset=utf-8` in the response headers. The Chrome browser also outputs some warning in this case:

`Resource interpreted as Stylesheet but transferred with MIME type text/plain: "http://localhost:8080/xxx.css".`

The integrated webserver correctly responds with `content-type: text/css`.

**Comment by kelunik** [comment]
Should be fixed by #11. If not, please report back.
