### ISSUE TITLE
Output from STDOUT / STDERR is not captured

### ISSUE THREAD

**Issue by krlv** [kelunik/gateway#8]
While testing Gateway vs Symfony's built-in dev server vs PHP built-in servers turns out that Gateway doesn't capture output from `php://stderr` ~and `php://stdout`~

Symfony dev server output:
```
2018-12-20T08:46:46+00:00 [info] Matched route "about".
[Thu Dec 20 00:46:46 2018] 127.0.0.1:59806 [200]: /about
```

PHP built-in server output:
```
2018-12-20T08:44:47+00:00 [info] Matched route "about".
[Thu Dec 20 00:44:47 2018] 127.0.0.1:59794 [200]: /about
```

Gateway output (with `-e development`):
```
[2018-12-20 09:25:46] server.info: [200] GET /about @ 127.0.0.1:60188 [] []
```
As you can see, there is no INFO message in Gateway's output.

**Comment by krlv** [comment]
@kelunik if you have a hint how this can be easily fixed, I'm more than happy to help

**Comment by kelunik** [comment]
`php://stdout` is the response sent to the client, so it's probably `php://stderr`? It's already captured, but not forwarded, yet.

**Comment by krlv** [comment]
Sorry, my bad, I meant only `php://stderr` (that's what you get creating issue at 3am 🙈)

Yes, I saw that `stderr` is captured in the `CgiRequestHandler::handleRequest`. But request handler  has no logger instance to send these `$errors` to. So the easiest way is to inject a logger instance to `CgiRequestHandler` class. This way we will have nice and shiny `AccessLogMiddleware` for access logs, and _"not that nice"_ CGI Request Handler with error logs logic in it (tbh don't like this solution)

From what I see it, maybe it is `Server`'s responsibility to handle error logs?

Looking forward for your advice 🙇

**Comment by kelunik** [comment]
We can either do that, or use the `Server`'s logger directly via an `onStart()` handler (`ServerObserver`).

**Comment by kelunik** [comment]
I've pushed a fix, please test it.

**Comment by krlv** [comment]
Confirmed, works as expected. 

BTW, an elegant fix you done 👍   (didn't know the `Amp\Promise\rethrow` exists)

**Comment by kelunik** [comment]
😊
