### ISSUE TITLE
Wrong HTTP status for missing resources

### ISSUE THREAD

**Issue by krlv** [kelunik/gateway#9]
Gateway displays wrong HTTP status for static files that are actually missing.

Currently, there is no `/favicon.png` file in my public folder, but this file is linked in HTML template

```html
<html><head><link rel="icon" type="image/png" href="favicon.png"></head><body>...</body></html>
```

Here is the output from Gateway:

```shell
[2018-12-20 09:25:46] server.info: [200] GET /about @ 127.0.0.1:60188 [] []
[2018-12-20 09:25:46] server.info: [200] GET /favicon.png @ 127.0.0.1:60188 [] []
```

I decided to test this case with Symfony's and PHP built-in dev servers. Here are the results:

Symfony dev server output (have the same problem):
```shell
2018-12-20T08:46:46+00:00 [info] Matched route "about".
[Thu Dec 20 00:46:46 2018] 127.0.0.1:59806 [200]: /about
2018-12-20T08:46:46+00:00 [info] Matched route "index".
[Thu Dec 20 00:46:46 2018] 127.0.0.1:59807 [200]: /favicon.png
```

PHP built-in server output (the one who handles this right):
```shell
2018-12-20T08:45:42+00:00 [info] Matched route "about".
[Thu Dec 20 00:45:42 2018] 127.0.0.1:59798 [200]: /about
[Thu Dec 20 00:45:42 2018] 127.0.0.1:59799 [404]: /favicon.png - No such file or directory
```

**Comment by kelunik** [comment]
The issue here seems to be that your front-controller script doesn't send a 404 response, no? Could you share a script that reproduces the issue?

**Comment by krlv** [comment]
You're right, my front controller handles it with 200 response. In my project, Nginx handles 404 for static / assets. The interesting part is, that PHP's built-in server somehow able to return 404 for this case, when Symfony and Gateway forward request to front controller.

So I assume, it's expected behavior for Gateway, rather than a bug? If so, feel free to close it. 👍

**Comment by kelunik** [comment]
Same here, not sure what the built in server does.
